apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: external-forward
spec:
  homepage: https://github.com/int128/kubectl-external-forward
  shortDescription: Connect to external host via cluster
  description: |
    This runs a TCP proxy to connect from your laptop to an external host via a cluster.
    It is useful when a host such as database is in a private network and unreachable from your laptop.
    While `kubectl port-forward` connects to an internal pod only, this plugin connects to an external host.
    No proxy configuration such as HTTP_PROXY or SOCKS is needed.

  version: {{ .TagName }}
  platforms:
  - bin: kubectl-external_forward
    {{ addURIAndSha "https://github.com/int128/kubectl-external-forward/releases/download/{{ .TagName }}/kubectl-external_forward_linux_amd64.zip" .TagName }}
    selector:
      matchLabels:
        os: linux
        arch: amd64
  - bin: kubectl-external_forward
    {{ addURIAndSha "https://github.com/int128/kubectl-external-forward/releases/download/{{ .TagName }}/kubectl-external_forward_linux_arm64.zip" .TagName }}
    selector:
      matchLabels:
        os: linux
        arch: arm64
  - bin: kubectl-external_forward
    {{ addURIAndSha "https://github.com/int128/kubectl-external-forward/releases/download/{{ .TagName }}/kubectl-external_forward_linux_arm.zip" .TagName }}
    selector:
      matchLabels:
        os: linux
        arch: arm
  - bin: kubectl-external_forward
    {{ addURIAndSha "https://github.com/int128/kubectl-external-forward/releases/download/{{ .TagName }}/kubectl-external_forward_darwin_amd64.zip" .TagName }}
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - bin: kubectl-external_forward
    {{ addURIAndSha "https://github.com/int128/kubectl-external-forward/releases/download/{{ .TagName }}/kubectl-external_forward_darwin_arm64.zip" .TagName }}
    selector:
      matchLabels:
        os: darwin
        arch: arm64
  - bin: kubectl-external_forward
    {{ addURIAndSha "https://github.com/int128/kubectl-external-forward/releases/download/{{ .TagName }}/kubectl-external_forward_windows_amd64.zip" .TagName }}
    selector:
      matchLabels:
        os: windows
        arch: amd64
